# Import Required Libraries

In [20]:
import pandas as pd

# Load Dataset

In [25]:
# Load the sentimentdataset.csv file into a pandas DataFrame
df = pd.read_csv('sentimentdataset.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

# Preprocess dataset

In [26]:
# Rename the 'Sentiment' column to 'SentimentCategory'
df.rename(columns={'Sentiment': 'SentimentCategory'}, inplace=True)
# Remove all the blank spaces at the beginning and at the end of the 'SentimentCategory' column
df['SentimentCategory'] = df['SentimentCategory'].str.strip()
df.head()

,Unnamed: 0.1,Unnamed: 0,Text,SentimentCategory,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

## Map SentimentCategory to Numeric Values

In [28]:
# Define the sentiment mapping dictionary
sentiment_mapping = {
    # Strongly Negative (0.0â€“0.2)
    'Negative': 0.0, 'Hate': 0.0, 'Despair': 0.1, 'Grief': 0.1, 'Sorrow': 0.1,
    'Loneliness': 0.1, 'Helplessness': 0.1, 'Betrayal': 0.1, 'Frustration': 0.2,
    'Anger': 0.2, 'Resentment': 0.2, 'Disgust': 0.2, 'Fear': 0.2, 'Jealousy': 0.2,
    'Anxiety': 0.2, 'Regret': 0.2, 'Intimidation': 0.2, 'Bitterness': 0.2,
    'Heartbreak': 0.1, 'Devastated': 0.1, 'Desperation': 0.1, 'Melancholy': 0.2,
    'Darkness': 0.1, 'Isolation': 0.1, 'Suffering': 0.1, 'Exhaustion': 0.2,
    'Boredom': 0.2, 'Shame': 0.2, 'Envy': 0.2, 'Bad': 0.2, 'Fearful': 0.2,
    'Apprehensive': 0.2, 'Dismissive': 0.2, 'Disappointed': 0.2,
    'LostLove': 0.1, 'Ruins': 0.1, 'Desolation': 0.1, 'Loss': 0.1,
    'Heartache': 0.1, 'EmotionalStorm': 0.1, 'Obstacle': 0.2,
    'Miscalculation': 0.2, 'Challenge': 0.2, 'Sadness': 0.2, 'Sad': 0.2,

    # Neutral (0.3â€“0.5)
    'Neutral': 0.5, 'Confusion': 0.4, 'Indifference': 0.4, 'Numbness': 0.4,
    'Ambivalence': 0.4, 'Reflection': 0.5, 'Calmness': 0.5, 'Serenity': 0.5,
    'Acceptance': 0.5, 'Contentment': 0.5, 'Pensive': 0.5, 'Contemplation': 0.5,
    'Appreciation': 0.5, 'Sympathy': 0.5, 'Pressure': 0.5, 'Relief': 0.5,
    'Bittersweet': 0.5, 'Solitude': 0.5, 'Renewed Effort': 0.5,

    # Weakly Positive (0.6â€“0.7)
    'Hopeful': 0.6, 'Gratitude': 0.6, 'Admiration': 0.7, 'Affection': 0.7,
    'Anticipation': 0.6, 'Pride': 0.6, 'Compassion': 0.7, 'Determination': 0.6,
    'Tenderness': 0.7, 'Calmness': 0.6, 'Harmony': 0.6, 'Kindness': 0.7,
    'Friendship': 0.7, 'Playful': 0.7, 'Confidence': 0.7, 'Enthusiasm': 0.7,
    'Inspiration': 0.7, 'Curiosity': 0.6, 'Optimism': 0.7, 'Motivation': 0.7,
    'Empathetic': 0.7, 'Zest': 0.7, 'Spark': 0.7, 'Intrigue': 0.6,
    'DreamChaser': 0.7, 'Creativity': 0.7, 'Coziness': 0.7, 'InnerJourney': 0.7,
    'Adrenaline': 0.7, 'Imagination': 0.7, 'Vibrancy': 0.7, 'Proud': 0.7,
    'Yearning': 0.6, 'Frustrated': 0.6, 'Envious': 0.6, 'Empowerment': 0.7,
    'Resilience': 0.7, 'PlayfulJoy': 0.7, 'Accomplishment': 0.7,
    'Immersion': 0.7, 'Solace': 0.7,

    # Strongly Positive (0.8â€“1.0)
    'Positive': 1.0, 'Joy': 0.9, 'Happiness': 0.9, 'Euphoria': 0.95,
    'Excitement': 0.9, 'Love': 0.9, 'Amusement': 0.9, 'Enjoyment': 0.9,
    'Adoration': 0.9, 'Awe': 0.9, 'Thrill': 0.9, 'Overjoyed': 0.9,
    'Satisfaction': 0.9, 'Grateful': 0.9, 'Triumph': 0.9, 'Success': 0.9,
    'Ecstasy': 0.95, 'Harmony': 0.9, 'Serenity': 0.9, 'Adventure': 0.9,
    'Wonder': 0.9, 'Radiance': 0.9, 'Freedom': 0.9, 'Elegance': 0.9,
    'Fulfillment': 0.9, 'Rejuvenation': 0.9, 'Blessed': 0.9, 'Marvel': 0.9,
    'Whimsy': 0.9, 'Exploration': 0.9, 'Tranquility': 0.9, 'Celebration': 0.9,
    'Hope': 0.9, 'JoyfulReunion': 0.9, 'Grandeur': 0.9, 'Charm': 0.9,
    'Overwhelmed': 0.8, 'Reverence': 0.8, 'Heartwarming': 0.8, 'Confidence': 0.8,
    'Mindfulness': 0.8, 'Grateful': 0.8, 'Kind': 0.8, 'Empowered': 0.8,
    'Inspired': 0.8, 'Touched': 0.8, 'Free-spirited': 0.8, 'Positivity': 0.8,
    'Creative': 0.8, 'Colorful': 0.8, 'Hypnotic': 0.8, 'Compassionate': 0.8,
    'Elation': 0.9, 'Nostalgia': 0.8, 'Reflection': 0.8, 'Wholesome': 0.9,
    'Wonderment': 0.8, 'Joy in Baking': 0.9, 'Natureâ€™s Beauty': 0.9,
    'FestiveJoy': 0.9, 'Winter Magic': 0.9, 'Euphoria': 0.95, 'Melodic': 0.9,
    'ArtisticBurst': 0.9, 'CulinaryOdyssey': 0.9, 'Dazzle': 0.9,
    'Enchantment': 0.8, 'Amazement': 0.9, 'Romance': 0.9, 'Captivation': 0.9,
    'Emotion': 0.8, 'Connection': 0.8, 'Iconic': 0.8, 'Journey': 0.8,
    'Engagement': 0.8, 'Suspense': 0.8, 'Culinary Adventure': 0.9,
    'Thrilling Journey': 0.9,
    
    # Other
    'Surprise': 0.7,
    'Bitter': 0.2,
    'Arousal': 0.7,
    'Confident': 0.8,
    'Jealous': 0.2,
    'Disappointment': 0.2,
    'Energy': 0.8,
    'Breakthrough': 0.8,
    'Envisioning History': 0.7,
    'Mesmerizing': 0.9,
    "Nature's Beauty": 0.9,
    'Celestial Wonder': 0.9,
    'Creative Inspiration': 0.9,
    'Runway Creativity': 0.9,
    "Ocean's Freedom": 0.9,
    'Whispers of the Past': 0.8,
    'Embarrassed': 0.3,
    'Mischievous': 0.7,
    'Happy': 0.9
}

# Map the 'SentimentCategory' to numeric values using the sentiment_mapping dictionary
df['sentiment'] = df['SentimentCategory'].map(sentiment_mapping)
df.head(10)

,Unnamed: 0.1,Unnamed: 0,Text,SentimentCategory,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,sentiment
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12,1.0
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8,0.0
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15,1.0
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18,1.0
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19,0.5
5,5,5,Feeling grateful for the little things in lif...,Positive,2023-01-16 09:10:00,GratitudeNow,Twitter,#Gratitude #PositiveVibes,25.0,50.0,India,2023,1,16,9,1.0
6,6,6,Rainy days call for cozy blankets and hot coc...,Positive,2023-01-16 14:45:00,RainyDays,Facebook,#RainyDays #Cozy,10.0,20.0,Canada,2023,1,16,14,1.0
7,7,7,The new movie release is a must-watch! ...,Positive,2023-01-16 19:30:00,MovieBuff,Instagram,#MovieNight #MustWatch,15.0,30.0,USA,2023,1,16,19,1.0
8,8,8,Political discussions heating up on the timel...,Negative,2023-01-17 08:00:00,DebateTalk,Twitter,#Politics #Debate,30.0,60.0,USA,2023,1,17,8,0.0
9,9,9,Missing summer vibes and beach days. ...,Neutral,2023-01-17 12:20:00,BeachLover,Facebook,#Summer #BeachDays,18.0,35.0,Australia,2023,1,17,12,0.5

In [30]:
# Check the number of null values in the 'sentiment' column
df['sentiment'].isnull().sum()

# # Find the rows where 'sentiment' is null
# null_sentiment_rows = df[df['sentiment'].isnull()]
# # Get the distinct 'SentimentCategory' values for those rows
# distinct_null_categories = null_sentiment_rows['SentimentCategory'].unique()
# # Print the distinct 'SentimentCategory' values
# print("Distinct SentimentCategory values for null sentiments:")
# print(distinct_null_categories)

0

In [31]:
# Ensure the 'Timestamp' column is in datetime format
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
# Create the 'year' column based on the 'Timestamp' column
df['year'] = df['Timestamp'].dt.year
# Create the 'time' column with the desired format
df['time'] = df['Timestamp'].dt.strftime('%Y-%m-%dT%H:%M:%S')
# Display the first few rows of the DataFrame to verify the changes
df.head()

,Unnamed: 0.1,Unnamed: 0,Text,SentimentCategory,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,sentiment,year,time
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12,1.0,2023,2023-01-15T12:30:00
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8,0.0,2023,2023-01-15T08:45:00
2,2,2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15,1.0,2023,2023-01-15T15:45:00
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18,1.0,2023,2023-01-15T18:20:00
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19,0.5,2023,2023-01-15T19:55:00

In [32]:
# Remove the first two columns
df = df.iloc[:, 2:]
# Add a new column named 'source' with the value 'socialmedia' for all rows
df['source'] = 'socialmedia'
# Display the first few rows of the DataFrame to verify the changes
df.head()

,Text,SentimentCategory,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour,sentiment,year,time,source
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12,1.0,2023,2023-01-15T12:30:00,socialmedia
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8,0.0,2023,2023-01-15T08:45:00,socialmedia
2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15,1.0,2023,2023-01-15T15:45:00,socialmedia
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18,1.0,2023,2023-01-15T18:20:00,socialmedia
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19,0.5,2023,2023-01-15T19:55:00,socialmedia

In [33]:
# Remove all empty spaces from the 'Hashtags' column
df['Hashtags'] = df['Hashtags'].str.replace(' ', '')
# Split the 'Hashtags' column into multiple columns whenever '#' occurs
hashtags_split = df['Hashtags'].str.split('#', expand=True)
# Drop the original 'Hashtags' column
df = df.drop(columns=['Hashtags'])
# Rename the split columns and add them to the DataFrame
for i in range(1, hashtags_split.shape[1]):
    df[f'Hashtag_{i}'] = hashtags_split[i]
# Display the first few rows of the DataFrame to verify the changes
df.head()

,Text,SentimentCategory,Timestamp,User,Platform,Retweets,Likes,Country,Year,Month,Day,Hour,sentiment,year,time,source,Hashtag_1,Hashtag_2
0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,15.0,30.0,USA,2023,1,15,12,1.0,2023,2023-01-15T12:30:00,socialmedia,Nature,Park
1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,5.0,10.0,Canada,2023,1,15,8,0.0,2023,2023-01-15T08:45:00,socialmedia,Traffic,Morning
2,Just finished an amazing workout! ðŸ’ª ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,20.0,40.0,USA,2023,1,15,15,1.0,2023,2023-01-15T15:45:00,socialmedia,Fitness,Workout
3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,8.0,15.0,UK,2023,1,15,18,1.0,2023,2023-01-15T18:20:00,socialmedia,Travel,Adventure
4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,12.0,25.0,Australia,2023,1,15,19,0.5,2023,2023-01-15T19:55:00,socialmedia,Cooking,Food

In [34]:
# Remove the specified columns
df = df.drop(columns=['Timestamp', 'Year', 'Month', 'Day', 'Hour'])
# Display the first few rows of the DataFrame to verify the changes
df.head()

,Text,SentimentCategory,User,Platform,Retweets,Likes,Country,sentiment,year,time,source,Hashtag_1,Hashtag_2
0,Enjoying a beautiful day at the park! ...,Positive,User123,Twitter,15.0,30.0,USA,1.0,2023,2023-01-15T12:30:00,socialmedia,Nature,Park
1,Traffic was terrible this morning. ...,Negative,CommuterX,Twitter,5.0,10.0,Canada,0.0,2023,2023-01-15T08:45:00,socialmedia,Traffic,Morning
2,Just finished an amazing workout! ðŸ’ª ...,Positive,FitnessFan,Instagram,20.0,40.0,USA,1.0,2023,2023-01-15T15:45:00,socialmedia,Fitness,Workout
3,Excited about the upcoming weekend getaway! ...,Positive,AdventureX,Facebook,8.0,15.0,UK,1.0,2023,2023-01-15T18:20:00,socialmedia,Travel,Adventure
4,Trying out a new recipe for dinner tonight. ...,Neutral,ChefCook,Instagram,12.0,25.0,Australia,0.5,2023,2023-01-15T19:55:00,socialmedia,Cooking,Food

# Melt

## option1: keep info

In [35]:
# # Unpivot the 'Hashtag_1' and 'Hashtag_2' columns
# df_melted = df.melt(id_vars=['Text', 'SentimentCategory', 'User', 'Platform', 'Retweets', 'Likes', 'Country', 'sentiment', 'year', 'time', 'source'],
#                     value_vars=['Hashtag_1', 'Hashtag_2'],
#                     var_name='Hashtag_Type',
#                     value_name='Hashtag')

# # Drop rows with missing values in the 'Hashtag' column
# df_melted = df_melted.dropna(subset=['Hashtag'])

# # Drop the 'Hashtag_Type' column as it is no longer needed
# df_melted = df_melted.drop(columns=['Hashtag_Type'])

# # Display the first few rows of the transformed DataFrame to verify the changes
# df_melted.head()

,Text,SentimentCategory,User,Platform,Retweets,Likes,Country,sentiment,year,time,source,Hashtag
0,Enjoying a beautiful day at the park! ...,Positive,User123,Twitter,15.0,30.0,USA,1.0,2023,2023-01-15T12:30:00,socialmedia,Nature
1,Traffic was terrible this morning. ...,Negative,CommuterX,Twitter,5.0,10.0,Canada,0.0,2023,2023-01-15T08:45:00,socialmedia,Traffic
2,Just finished an amazing workout! ðŸ’ª ...,Positive,FitnessFan,Instagram,20.0,40.0,USA,1.0,2023,2023-01-15T15:45:00,socialmedia,Fitness
3,Excited about the upcoming weekend getaway! ...,Positive,AdventureX,Facebook,8.0,15.0,UK,1.0,2023,2023-01-15T18:20:00,socialmedia,Travel
4,Trying out a new recipe for dinner tonight. ...,Neutral,ChefCook,Instagram,12.0,25.0,Australia,0.5,2023,2023-01-15T19:55:00,socialmedia,Cooking

## option2: aggregate by year

In [36]:
# Remove the specified columns
df = df.drop(columns=['Text', 'SentimentCategory', 'User', 'Platform', 'Retweets', 'Likes', 'Country'])
df.head()

   sentiment  year                 time       source Hashtag_1  Hashtag_2
0        1.0  2023  2023-01-15T12:30:00  socialmedia    Nature       Park
1        0.0  2023  2023-01-15T08:45:00  socialmedia   Traffic    Morning
2        1.0  2023  2023-01-15T15:45:00  socialmedia   Fitness    Workout
3        1.0  2023  2023-01-15T18:20:00  socialmedia    Travel  Adventure
4        0.5  2023  2023-01-15T19:55:00  socialmedia   Cooking       Food

In [39]:
# Melt the DataFrame to have each row correspond to a single 'Hashtag'
df_melted = df.melt(id_vars=['sentiment', 'year', 'time', 'source'], 
                    value_vars=['Hashtag_1', 'Hashtag_2'], 
                    var_name='HashtagType', 
                    value_name='Hashtag')

# Drop the 'HashtagType' column as it is no longer needed
df_melted = df_melted.drop(columns=['HashtagType'])

# Drop rows with missing values in the 'Hashtag' column
df_melted = df_melted.dropna(subset=['Hashtag'])
df_melted.head()

   sentiment  year                 time       source  Hashtag
0        1.0  2023  2023-01-15T12:30:00  socialmedia   Nature
1        0.0  2023  2023-01-15T08:45:00  socialmedia  Traffic
2        1.0  2023  2023-01-15T15:45:00  socialmedia  Fitness
3        1.0  2023  2023-01-15T18:20:00  socialmedia   Travel
4        0.5  2023  2023-01-15T19:55:00  socialmedia  Cooking

In [40]:
# Rename the 'Hashtag' column to 'text' and convert it to lowercase
df_melted.rename(columns={'Hashtag': 'text'}, inplace=True)
df_melted['text'] = df_melted['text'].str.lower()
# Reorder the columns
df_melted = df_melted[['source', 'year', 'time', 'text', 'sentiment']]
df_melted.head()

        source  year                 time     text  sentiment
0  socialmedia  2023  2023-01-15T12:30:00   nature        1.0
1  socialmedia  2023  2023-01-15T08:45:00  traffic        0.0
2  socialmedia  2023  2023-01-15T15:45:00  fitness        1.0
3  socialmedia  2023  2023-01-15T18:20:00   travel        1.0
4  socialmedia  2023  2023-01-15T19:55:00  cooking        0.5

In [41]:
# Remove the 'time' column
df_melted = df_melted.drop(columns=['time'])

# Aggregate by 'text' and 'year' and create a new 'frequency' column
df_aggregated = df_melted.groupby(['source', 'year', 'text', 'sentiment']).size().reset_index(name='frequency')
df_aggregated.head()

        source  year         text  sentiment  frequency
0  socialmedia  2010  contentment        0.5          2
1  socialmedia  2010      elation        0.9          1
2  socialmedia  2010         love        0.5          1
3  socialmedia  2010     memories        0.9          1
4  socialmedia  2010   sundaymood        0.5          1

# Save Preprocessed dataset

In [42]:
# # Save the preprocessed DataFrame to a new CSV file
# Export the DataFrame to a new .tsv file
df_aggregated.to_csv('SocialMedia_sentiment.tsv', sep='\t', index=False)